on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JS-DevTools/npm-publish@v3
        strategy: upgrade
        with:
          token: ${{ secrets.NPM_TOKEN }}
